# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/multica-ai/multica"
  version "0.4.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.26/multica-cli-0.4.26-darwin-amd64.tar.gz"
      sha256 "4c71b5f11474642b4355b78be9707d7278e2f8f08c20d50f52b7bae3e0f0553a"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.26/multica-cli-0.4.26-darwin-arm64.tar.gz"
      sha256 "da13c8480634c6af49d67150c15eac15f17747cfcb11887edddb443b753ce8ac"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.26/multica-cli-0.4.26-linux-amd64.tar.gz"
      sha256 "0b17d9f8868e0b9d158d70f07d5f817ecd6f138e0ba1db38b83412c9dc321f32"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.26/multica-cli-0.4.26-linux-arm64.tar.gz"
      sha256 "547c43c1b6d96be92747441ec2e2ccee7bf3df03fb03aa7321339d422d82c7ed"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
