# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/multica-ai/multica"
  version "0.4.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.16/multica-cli-0.4.16-darwin-amd64.tar.gz"
      sha256 "e346ac5144e41825a4afaf7b9fac0cc9ba318167176c54fc96e701ca56d4a913"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.16/multica-cli-0.4.16-darwin-arm64.tar.gz"
      sha256 "b3fc50d3b43d4fe5d46ea456f0fc7b99c43d8356acb836d1a7d57067f5e84b94"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.16/multica-cli-0.4.16-linux-amd64.tar.gz"
      sha256 "ff32b237eb224cb8cc0864f436615af3c88be26b43b8b2d2440cf6bae905321d"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/multica-ai/multica/releases/download/v0.4.16/multica-cli-0.4.16-linux-arm64.tar.gz"
      sha256 "1a1e5c49c173789012a3d62398e20371ca2f1e38ea320557e052e6b352b6f251"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
